# Label Encoding:

### Converts categories into numeric labels.
### For example, if you have a column "Color" with values: ['Red', 'Blue', 'Green'], label encoding would convert them into numbers like: Red → 0, Blue → 1, Green → 2




In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.DataFrame(
    {
       'color':['red','blue','green','red','blue']
    }
)

In [4]:
lbl_encoder=LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

## Ordinal Encoding :- it is used to encode categorical data that have an intrinsic order or ranking 
### in this technique each category is assigned a numerical value based on its position in the order .
### example:- HighSchool-1, college -2, graduates -3, PostGraduates-4

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [9]:
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [11]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [12]:
encoder_df=encoder.fit_transform(df[['size']])

In [13]:
encoder_df

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [17]:
encoder.transform([['small']])

c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [23]:
encoder_df2=pd.DataFrame(encoder_df,columns=encoder.get_feature_names_out())

In [24]:
encoder_df2

size
0   0.0
1   1.0
2   2.0
3   1.0
4   0.0
5   2.0

## Target_Guided Ordinal Encoding:
#### Target Guided Ordinal Encoding is a type of categorical encoding where the categories are sorted based on their relationship with the target variable. This encoding method is especially useful in supervised learning problems, as it creates an order in the categorical data based on how it impacts the target variable (such as a regression value or classification label).

In [25]:
df=pd.DataFrame({
    'city':['london','singapore','delhi','tokyo','paris'],
    'price':[200,150,100,300,400]
})

In [26]:
mean_price=df.groupby('city')['price'].mean()

In [27]:
df['city_encoded']=df['city'].map(mean_price)

In [29]:
df[['price','city_encoded']]

price  city_encoded
0    200         200.0
1    150         150.0
2    100         100.0
3    300         300.0
4    400         400.0

In [49]:
tips=sns.load_dataset('tips')
print(tips.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


In [50]:
mean_tips_per_day=tips.groupby('day')['tip'].mean()

C:\Users\Aftab\AppData\Local\Temp\ipykernel_4960\22241293.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_tips_per_day=tips.groupby('day')['tip'].mean()


In [51]:
print(mean_tips_per_day)

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64


In [53]:
df_encoded=tips['day'].map(mean_tips_per_day)

In [56]:
df_encoded

0      3.255132
1      3.255132
2      3.255132
3      3.255132
4      3.255132
         ...   
239    2.993103
240    2.993103
241    2.993103
242    2.993103
243    2.771452
Name: day, Length: 244, dtype: category
Categories (4, float64): [2.771452, 2.734737, 2.993103, 3.255132]