## Numpy Library in Python


In [1]:
import numpy as np

In [2]:
arr1=np.arange(0,6)
print(arr1)

[0 1 2 3 4 5]


In [3]:
arr1.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [4]:
arr1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
np.arange(0,10,3).reshape(2,2)

array([[0, 3],
       [6, 9]])

In [8]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
## Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])

## elements wise addition

print("Addition",arr1+arr2)
print("Substraction",arr2-arr1)
print("mulpn",arr2*arr1)
print("Division",arr2/arr1)


Addition [ 6  8 10 12 14]
Substraction [4 4 4 4 4]
mulpn [ 5 12 21 32 45]
Division [5.         3.         2.33333333 2.         1.8       ]


In [12]:
## Universal Function
arr=np.array([2,3,4,5,9])
## square root
print(np.sqrt(arr))
## sin operation
print(np.sin(arr))
## natural log
print(np.log10(arr))



[1.41421356 1.73205081 2.         2.23606798 3.        ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849]
[0.30103    0.47712125 0.60205999 0.69897    0.95424251]


In [14]:
lst=np.arange(1,10).reshape(3,3)

In [15]:
print(lst)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
lst[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
lst[0][0]

1

In [18]:
lst[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
lst[0:2,1:]

array([[2, 3],
       [5, 6]])

In [25]:
## modifying array elements

lst[0,1]=100

In [26]:
lst

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [28]:
## stastical concept -- Normalisation
## calulate the mean and standard deviation of given data
data =np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)

## Normalize the data
normalized_data=(data-mean)/std_dev

print("Normalized data is :",normalized_data)

Normalized data is : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
## Mean Median Standard deviation and variance
data=np.arange(0,11)
mean=np.mean(data)
median=np.median(data)
std_dev=np.std(data)
variance=np.var(data)