## Logistic Regression Implementation.

In [4]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as Plt
%matplotlib inline
import seaborn as sns


In [5]:
from sklearn.datasets import make_classification

In [6]:
## creating the dataset
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=15)

In [7]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -0.377957  1.043895  1.043494 -0.101838 -1.617442  0.402713  0.913601   
1   -0.325259  1.276263 -0.686123 -2.463205 -0.489426 -0.240715 -1.469496   
2    0.739019 -0.600903 -0.177294  1.335714 -0.817332 -0.790047  1.457365   
3    0.474312 -1.103002  1.189936 -0.800186  0.912377 -0.406451 -1.130950   
4    0.927365  1.114796  0.080284  1.261064  0.761179  0.921563  0.440832   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.538272  0.171629  0.075371 -0.957658 -1.066219  1.158096 -0.036964   
996 -0.060266  0.095018 -0.271685  1.830560  0.219445 -0.341269  1.180088   
997  0.675563 -0.538420 -1.299500  0.747835  1.733898 -0.268044 -0.520953   
998  2.629710 -2.452899 -1.359785  1.592065  0.854157  1.618828  0.621701   
999 -1.791491 -0.121908  0.535153 -0.588085 -1.929461 -0.659900  0.754921   

            7         8         9  
0   -0.067192  0.175471 -1.049646  
1    1.006633 -0.833692  0.957744  
2   -0.218981  0.878643 -1.257740  
3    1.985111  1.379029  1.041768  
4    0.184645 -1.567739 -0.142107  
..        ...       ...       ...  
995  0.123689  0.927871 -0.225003  
996 -0.216876 -1.752938 -0.810152  
997  2.043336  0.947388  0.790354  
998  0.378898 -1.971894 -0.252250  
999 -1.941357  0.589002 -1.007482  

[1000 rows x 10 columns]

In [8]:
y

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [9]:
## Train test split for the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=12)

In [10]:
## model selection
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()
logistic.fit(X_train,y_train)

LogisticRegression()

In [11]:
y_pred=logistic.predict(X_test)
print(y_pred)

[0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 1
 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 0
 1 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1
 1 1 1 1 1 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1
 1 0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0
 0 1 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1
 0 1 0 0]


In [12]:
## finding performance metrics for the above model.
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.9333333333333333
[[139   5]
 [ 15 141]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93       144
           1       0.97      0.90      0.93       156

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.94      0.93      0.93       300



## Hyperparameter Tuning And Cross Validation.

## Hyperparameter Tuning:
#### Hyperparameters are parameters that are set before the learning process begins (e.g., learning rate, number of trees in a random forest, number of hidden layers in a neural network). Unlike model parameters (like weights in a neural network), hyperparameters are not learned directly from the data.

##### Hyperparameter Tuning is the process of selecting the best combination of hyperparameters to improve model performance. This involves trying different values and configurations to find the most optimal settings for a given model.

#### Examples of Hyperparameters:

k in k-Nearest Neighbors (kNN)
Learning rate in Gradient Descent
Number of trees in Random Forest
Kernel type in Support Vector Machines (SVM)

#### Methods for Hyperparameter Tuning:

1. Grid Search – Tests all possible combinations of hyperparameters.
2. Random Search – Randomly selects combinations of hyperparameters to evaluate.
3. Bayesian Optimization – Uses probability models to find the best parameters.
5. Genetic Algorithms – Uses evolutionary techniques to optimize hyperparameters.
6. Automated Tools – Libraries like Optuna, Hyperopt, and Scikit-Learn's RandomizedSearchCV.

## Cross-Validation (CV):
#### Cross-validation is a technique for assessing the performance and generalization ability of a machine learning model. It divides the dataset into multiple parts to ensure the model is evaluated on different subsets of data, reducing the risk of overfitting or underfitting.

#### How Cross-Validation Works:

The dataset is split into k equal parts (folds).
The model is trained on k-1 folds and validated on the remaining 1 fold.
This process repeats k times, with each fold serving as a validation set once.
The average performance across all k-folds provides a robust estimate of model performance.

#### Types of Cross-Validation:

1. K-Fold Cross-Validation – Divides data into k subsets.
2. Stratified K-Fold – Ensures class distribution is preserved in each fold.
3. Leave-One-Out (LOO) – Uses one data point for validation and the rest for training.
4. Time-Series Split – For sequential data, ensuring past data is used to predict future data.
5. Importance of Hyperparameter Tuning and Cross-Validation:
6. Improved Model Performance – Tuning helps the model learn more effectively, while cross-validation provides 7. a better measure of how well the model will perform on unseen data.
8. Reduces Overfitting – Cross-validation ensures the model generalizes well, preventing it from memorizing the training data.
9. Efficient Use of Data – Cross-validation makes full use of the dataset for both training and validation.
10. Model Comparisons – Helps in comparing different models or hyperparameter configurations fairly.
11. Robustness and Reliability – The combination of tuning and validation leads to models that are more reliable in real-world scenarios.








In [13]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newfan-cg','lbfgs','liblinear','sag','saga']


In [16]:
param=dict(penalty=penalty,C=c_values,solver=solver)

In [17]:
## Grid SearchCv
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()


In [18]:
from sklearn.model_selection import GridSearchCV
gs=GridSearchCV(estimator=model,param_grid=param,scoring='accuracy',cv=cv)

In [19]:
gs.fit(X_train,y_train)

c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newfan-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [20]:
gs.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [21]:
gs.best_score_

0.9185714285714285

In [25]:
y_pred=gs.predict(X_test)


0.9366666666666666
[[141   3]
 [ 16 140]]
              precision    recall  f1-score   support

           0       0.90      0.98      0.94       144
           1       0.98      0.90      0.94       156

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300



0.9366666666666666
[[141   3]
 [ 16 140]]
              precision    recall  f1-score   support

           0       0.90      0.98      0.94       144
           1       0.98      0.90      0.94       156

    accuracy                           0.94       300
   macro avg       0.94      0.94      0.94       300
weighted avg       0.94      0.94      0.94       300

