In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [3]:
## building the model
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [4]:
X_train

array([[-0.49570585,  0.3598562 ,  0.60784034, ..., -0.18509765,
        -1.30365134,  1.2121292 ],
       [-0.40042021,  0.99726646,  0.23402445, ...,  1.81806192,
        -0.92493641,  0.77515549],
       [-0.10080568,  0.35288107, -0.06844649, ...,  0.97845781,
         0.63074899, -0.81052863],
       ...,
       [-1.10977309,  2.48592829,  0.16805981, ..., -0.71468068,
        -1.72451193,  0.52127991],
       [-0.31507469,  0.34865742,  0.14934191, ..., -0.69941454,
        -1.08711789,  0.16169853],
       [ 0.47811427, -1.79232572,  1.81889853, ...,  0.29523258,
         1.14338175, -0.23823368]])

In [5]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score,confusion_matrix
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]


In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, GridSearchCV

# Define the correct hyperparameters for Logistic Regression
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'solver': ['saga', 'liblinear'],
    'max_iter': [100, 200, 300]
}

# Initialize Logistic Regression model
model = LogisticRegression(multi_class='ovr')

# Stratified K-Fold Cross Validation
cv = StratifiedKFold(n_splits=5)

# Grid Search for Hyperparameter Tuning
grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=cv)
grid.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Hyperparameters:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)


c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter 

Best Hyperparameters: {'C': 0.01, 'max_iter': 300, 'penalty': 'l1', 'solver': 'saga'}
Best Accuracy: 0.6399999999999999


c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
150 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
75 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Aftab\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1291, in fit
    fold_coefs_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose, prefer=prefer)(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Aftab\anaconda3\