## Naive Byes Machine Learning Algorithm Implementation

In [7]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split
X,y=load_iris(return_X_y=True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=0)

In [6]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [9]:
from sklearn.naive_bayes import GaussianNB

In [10]:
gnb=GaussianNB()

In [11]:
gnb.fit(X_train,y_train)

GaussianNB()

In [12]:
y_pred=gnb.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred=y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [17]:
df=sns.load_dataset('tips')

In [18]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [21]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [22]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [23]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [25]:
X = df.iloc[:, df.columns != 'smoker']
y = df.iloc[:, df.columns == 'smoker']


In [26]:
X

total_bill   tip     sex   day    time  size
0         16.99  1.01  Female   Sun  Dinner     2
1         10.34  1.66    Male   Sun  Dinner     3
2         21.01  3.50    Male   Sun  Dinner     3
3         23.68  3.31    Male   Sun  Dinner     2
4         24.59  3.61  Female   Sun  Dinner     4
..          ...   ...     ...   ...     ...   ...
239       29.03  5.92    Male   Sat  Dinner     3
240       27.18  2.00  Female   Sat  Dinner     2
241       22.67  2.00    Male   Sat  Dinner     2
242       17.82  1.75    Male   Sat  Dinner     2
243       18.78  3.00  Female  Thur  Dinner     2

[244 rows x 6 columns]

In [27]:
y

smoker
0       No
1       No
2       No
3       No
4       No
..     ...
239     No
240    Yes
241    Yes
242     No
243     No

[244 rows x 1 columns]

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [24]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [55]:
import warnings
warnings.filterwarnings('ignore')

X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['time']=le3.fit_transform(X_train['time'])






In [53]:
X_train.head(5)

total_bill   tip  sex  day  time  size
234       15.53  3.00    1  Sat     0     2
227       20.45  3.00    1  Sat     0     4
180       34.65  3.68    1  Sun     0     4
5         25.29  4.71    1  Sun     0     4
56        38.01  3.00    1  Sat     0     4

In [35]:
from sklearn.preprocessing import LabelEncoder

# Assuming y_train contains the 'smoker' column
encoder = LabelEncoder()

# Fit and transform the y_train data
y_train = encoder.fit_transform(y_train)
y_train


array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [40]:
X_train_copy = X_train.drop('day', axis=1)


In [41]:
X_train_copy

total_bill   tip  sex  time  size
234       15.53  3.00    1     0     2
227       20.45  3.00    1     0     4
180       34.65  3.68    1     0     4
5         25.29  4.71    1     0     4
56        38.01  3.00    1     0     4
..          ...   ...  ...   ...   ...
106       20.49  4.06    1     0     2
14        14.83  3.02    0     0     2
92         5.75  1.00    0     0     2
179       34.63  3.55    1     0     2
102       44.30  2.50    0     0     3

[170 rows x 5 columns]

In [42]:
X_train_copy.head()

total_bill   tip  sex  time  size
234       15.53  3.00    1     0     2
227       20.45  3.00    1     0     4
180       34.65  3.68    1     0     4
5         25.29  4.71    1     0     4
56        38.01  3.00    1     0     4

In [43]:
X_train_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 170 entries, 234 to 102
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  170 non-null    float64
 1   tip         170 non-null    float64
 2   sex         170 non-null    int64  
 3   time        170 non-null    int32  
 4   size        170 non-null    int64  
dtypes: float64(2), int32(1), int64(2)
memory usage: 11.4 KB


In [44]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [45]:
gnb.fit(X_train_copy,y_train)

GaussianNB()

In [56]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoders for each categorical column
le_sex = LabelEncoder()
le_time = LabelEncoder()


# Handle test data (map unseen categories to -1)
X_test['sex'] = X_test['sex'].map(lambda x: le_sex.transform([x])[0] if x in le_sex.classes_ else -1)
X_test['time'] = X_test['time'].map(lambda x: le_time.transform([x])[0] if x in le_time.classes_ else -1)


AttributeError: 'LabelEncoder' object has no attribute 'classes_'

NotFittedError: This LabelEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.